### ISSUE TITLE
Exit with error when run MetaBinner 

### ISSUE THREAD

**Issue by dawnmy** [ziyewang/MetaBinner#10]
I run metabinner with the following cli:
```
run_metabinner.sh \
-a /vol/projects/dzhiluo/outputs/results/flye/S1/assembly.fasta \
-o /vol/projects/dzhiluo/outputs/results/metabinner \
-d /vol/projects/dzhiluo/outputs//results/read_coverage/S1.read_to_contig.metabinner.txt \
-k /vol/projects/dzhiluo/outputs/results/flye/S1/kmer_4_f1000.csv \
-p /home/dzhiluo/miniconda3/envs/binner/bin
```

but got the error:
```
Traceback (most recent call last):
  File "/home/dzhiluo/miniconda3/envs/binner/bin/scripts/split_hhbins.py", line 514, in <module>
    bins, contigs = read_bins_from_one_dir(path)
  File "/home/dzhiluo/miniconda3/envs/binner/bin/scripts/split_hhbins.py", line 426, in read_bins_from_one_dir
    bin_ext, count = get_bin_extension(bin_dir)
  File "/home/dzhiluo/miniconda3/envs/binner/bin/scripts/metabinner_util.py", line 166, in get_bin_extension
    for f in os.listdir(bin_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/vol/projects/dzhiluo/outputs/results/metabinner/metabinner_res/intermediate_result/partial_seed_kmeans_bacar_marker_seed_length_weight_1quarter_X_com_logtrans_result.tsv_bins'
partial_seed_kmeans_bacar_marker_seed_length_weight_1quarter_X_cov_logtrans_result.tsv
```

The output looks like:
```
outputs/results/metabinner/metabinner_res/
├── intermediate_result
│   ├── kmeans_length_weight_X_com_logtrans_result.tsv
│   ├── kmeans_length_weight_X_com_logtrans_result.tsv_bins
│   │   ├── 0.fa
│   │   └── 3.fa
│   ├── kmeans_length_weight_X_com_logtrans_result.tsv_bins_post_process_mincomp_70_mincont_50_bins
│   │   ├── 0.fa
│   │   └── 3.fa
│   ├── kmeans_length_weight_X_cov_logtrans_result.tsv
│   ├── kmeans_length_weight_X_cov_logtrans_result.tsv_bins
│   │   ├── 0.fa
│   │   └── 15.fa
│   ├── kmeans_length_weight_X_cov_logtrans_result.tsv_bins_post_process_mincomp_70_mincont_50_bins
│   │   ├── 0.fa
│   │   └── 15.fa
│   ├── kmeans_length_weight_X_t_logtrans_result.tsv
│   ├── kmeans_length_weight_X_t_logtrans_result.tsv_bins
│   │   ├── 0.fa
│   │   └── 16.fa
│   └── kmeans_length_weight_X_t_logtrans_result.tsv_bins_post_process_mincomp_70_mincont_50_bins
│       ├── 0.fa
│       └── 16.fa
├── intermediate_result.res_namelist.tsv
├── post_result.log
├── result.log
└── unitem_profile
    ├── binning_methods
    │   └── X_t_logtrans_ori
    ├── bin_quality_summary.tsv
    ├── bins_dir.tsv
    ├── kmeans_length_weight_X_t_logtrans_result.tsv
    ├── kmeans_length_weight_X_t_logtrans_result.tsv_bins
    │   ├── 0.fa
    │   └── 16.fa
    └── X_t_logtrans_ori_quality.tsv
```

How should I get it to run?

**Comment by ziyewang** [comment]
Hi,

Thanks for the report. If binning can finish successfully on the test data, this error may be that there are no contigs containing single-copy marker genes identified in these input sequences. MetaBinner only works on the dataset containing bacterial and archaeal genomes. Your dataset seems like a single-sample dataset. As stated in the manuscript (https://www.biorxiv.org/content/10.1101/2021.07.25.453671v1.full.pdf), we recommend applying MetaBinner to multi-sample datasets.

For single-sample datasets with few single-copy marker gene information, MetaBAT is a good choice.

Sorry to confuse you.

Best,
Ziye

**Comment by dawnmy** [comment]
Thank you for the detailed answer. Will rerun it as you suggested.
