### ISSUE TITLE
Something went wrong with running split_hhbins.py.

### ISSUE THREAD

**Issue by Georgios-Filis** [ziyewang/MetaBinner#24]
Dear Ziye Wang,
Thank you for your work. I have successfully installed MetaBinner via bioconda. I have run MetaBinner successfully in the past, but now I came across a problem which I cannot understand and I cannot overcome. I create the necessary files and run MetaBinner based on the following commands (after activating the environment of MetaBinner through conda):
1.
bash /home/user/anaconda3/envs/metabinner_env/bin/scripts/gen_coverage_file.sh -a /user_path/Contigs/Contigs_Formated.fna -o /user_path/Binning_Results/Coverages -t 6 -m 4 /user_path/Input/*fastq
2.
python /home/user/anaconda3/envs/metabinner_env/bin/scripts/gen_kmer.py /user_path/Contigs/Contigs_Formated.fna 1000 4
3.
python /home/user/anaconda3/envs/metabinner_env/bin/scripts/Filter_tooshort.py /user_path/Contigs/Contigs_Formated.fna 1000
4.
bash run_metabinner.sh -a /user_path/Contigs/Contigs_Formated.fna -o /user_path/Binning_Results/Bins -d /user_path/Binning_Results/Coverages/coverage_profile_f1k.tsv -k /user_path/Contigs/Contigs_Formated_kmer_4_f1000.csv -p /home/user/anaconda3/envs/metabinner_env/bin -t 6

The error I get is based on running "run_metabinner.sh" and it is the following:
1. Based on the output (at the final lines of the output):
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/metabinner_env/bin/scripts/split_hhbins.py", line 517, in <module>
    bins, contigs = read_bins_from_one_dir(path)
  File "/home/user/anaconda3/envs/metabinner_env/bin/scripts/split_hhbins.py", line 429, in read_bins_from_one_dir
    bin_ext, count = get_bin_extension(bin_dir)
  File "/home/user/anaconda3/envs/metabinner_env/bin/scripts/metabinner_util.py", line 166, in get_bin_extension
    for f in os.listdir(bin_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/user_path/Binning_Results/Bins/metabinner_res/intermediate_result/partial_seed_kmeans_bacar_marker_seed_length_weight_3quarter_X_t_logtrans_result.tsv_bins'
Something went wrong with running split_hhbins.py. Exiting.

2. The output also includes the following:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/metabinner_env/bin/scripts/split_hhbins.py", line 517, in <module>
    bins, contigs = read_bins_from_one_dir(path)
  File "/home/user/anaconda3/envs/metabinner_env/bin/scripts/split_hhbins.py", line 429, in read_bins_from_one_dir
    bin_ext, count = get_bin_extension(bin_dir)
  File "/home/user/anaconda3/envs/metabinner_env/bin/scripts/metabinner_util.py", line 166, in get_bin_extension
    for f in os.listdir(bin_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/user_path/Binning_Results/Bins/metabinner_res/intermediate_result/partial_seed_kmeans_bacar_marker_seed_length_weight_1quarter_X_com_logtrans_result.tsv_bins'
partial_seed_kmeans_bacar_marker_seed_length_weight_1quarter_X_cov_logtrans_result.tsv
/home/user/anaconda3/envs/metabinner_env/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.

3. The output also includes (at the beginning) the following:
2023-10-14 13:26:57,662 - markerCmd failed! Not exist: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_1quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /user_path/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.1quarter_lencutoff_1001.seed
...
2023-10-14 13:26:57,676 - markerCmd failed! Not exist: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_2quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /v/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.2quarter_lencutoff_1001.seed
...
2023-10-14 13:26:57,692 - markerCmd failed! Not exist: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_3quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /user_path/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.3quarter_lencutoff_1001.seed

4. The result log file includes the following:
2023-10-14 13:26:57,662 - markerCmd failed! Not exist: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_1quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /user_path/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.1quarter_lencutoff_1001.seed
2023-10-14 13:26:57,663 - bacar_marker_1quarter_seed_num:	0
2023-10-14 13:26:57,663 - exec cmd: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_2quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /user_path/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.2quarter_lencutoff_1001.seed
2023-10-14 13:26:57,676 - markerCmd failed! Not exist: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_2quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /user_path/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.2quarter_lencutoff_1001.seed
2023-10-14 13:26:57,677 - bacar_marker_2quarter_seed_num:	0
2023-10-14 13:26:57,677 - exec cmd: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_3quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /user_path/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.3quarter_lencutoff_1001.seed
2023-10-14 13:26:57,692 - markerCmd failed! Not exist: /home/user/anaconda3/envs/metabinner_env/bin/scripts/../auxiliary/test_getmarker_3quarter.pl /user_path/Contigs/Contigs_Formated.fna.bacar_marker.hmmout /user_path/Contigs/Contigs_Formated.fna 1001 /user_path/Contigs/Contigs_Formated.fna.bacar_marker.3quarter_lencutoff_1001.seed

5. The last lines of the post_result.log file are the following:
2023-10-14 13:27:25,539 - Contig_file:	/user_path/Contigs/Contigs_Formated.fna
2023-10-14 13:27:25,539 - Coverage_profiles:	/user_path/Binning_Results/Coverages/coverage_profile_f1k.tsv
2023-10-14 13:27:25,539 - Composition_profiles:	/user_path/Contigs/Contigs_Formated_kmer_4_f1000.csv
2023-10-14 13:27:25,539 - The binning result file to be handled:	/user_path/Binning_Results/Bins/metabinner_res/intermediate_result/partial_seed_kmeans_bacar_marker_seed_length_weight_3quarter_X_t_logtrans_result.tsv_bins
2023-10-14 13:27:25,539 - The number of threads:	6
2023-10-14 13:27:25,558 - The number of contigs:	14

6. The following files are retained in the contigs folder after the error:
Contigs_Formated.fna.bacar_marker.hmmout
Contigs_Formated.fna.bacar_marker.hmmout.err
Contigs_Formated.fna.bacar_marker.hmmout.out
Contigs_Formated.fna.bacar_marker.frag.err
Contigs_Formated.fna.bacar_marker.frag.faa
Contigs_Formated.fna.bacar_marker.frag.ffn
Contigs_Formated.fna.bacar_marker.frag.gff
Contigs_Formated.fna.bacar_marker.frag.out

**Comment by ziyewang** [comment]
Hi, Georgios-Filis

Thanks for using MetaBinner. Could you please provide additional information about the contigs, such as the number of contigs? Do the contigs primarily consist of bacterial or archaeal sequences? 

Could you please provide the "post_result.log" and "result.log" located in the result path "/user_path/Binning_Results/Bins/metabinner_res/"? Thanks very much.


Best wishes,
Ziye

**Comment by Georgios-Filis** [comment]
Dear Ziye Wang,
Thank you for your immediate response. The file with the contigs contains 1993 contigs. After filtering for contigs of length higher than 1000, 14 contigs remained. The (compressed) input FASTQ files have a size equal to 62 MBs and contain reads with lengths in the range of 25-36 nucleotides. The contigs probably primarily contain bacterial sequences.
I just run MetaBinner successfully based on another dataset of FASTQ files, of a few GBs in size, which contain reads with lengths in the range of 25-151 nucleotides which had formed 59408 contigs from which 16017 were above 1000 nucleotides in length. 

Therefore, could the error occur in the first case due to the low number of contigs or/and the small lengths of the reads?

I have attached the two log files related to the dataset of FASTQ and contig files that lead to the error.
[result.log](https://github.com/ziyewang/MetaBinner/files/12906523/result.log)
[post_result.log](https://github.com/ziyewang/MetaBinner/files/12906525/post_result.log)

Sincerely,
Giorgos

**Comment by ziyewang** [comment]
Hi, Giorgos

It seems that the contig count is low (14), and no single-copy marker genes (SCG) can be identified within these contigs. 

Best,
Ziye
